name: "CLA Signature Bot"
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened,closed,synchronize]

jobs:
  clabot:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.html_url, '/pull/')
    steps:
    - name: "CLA Signature Bot"
      uses: roblox/cla-signature-bot@v2.0.1-beta2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        whitelist: ""
        use-remote-repo: true
        remote-repo-name: "cliffchapmanrbx/TestClaRepo"
        remote-repo-pat: ${{ secrets.CLA_REMOTE_REPO_PAT }}
        url-to-cladocument: "https://roblox.github.io/cla-bot-store/"
        
